name: spicy_food_delivery
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  custom_navigation_bar: ^0.7.1
  font_awesome_flutter: ^8.12.0
  slide_to_act: ^0.1.3+1
  flutter_slidable: ^0.5.7
  flutter_xlider: ^3.4.0
  timelines: ^0.0.2+1
  flutter_svg: ^0.19.3
  pin_code_fields: ^6.0.1
  charts_flutter: ^0.9.0
  dotted_border: ^1.0.7
  circular_countdown_timer: ^0.1.0
  maps_launcher: ^1.0.1
  url_launcher:
  carousel_pro: ^1.0.0
  onesignal_flutter: ^3.0.0
  razorpay_flutter: ^1.2.7


  cloud_firestore: ^2.4.0
  firebase_core: ^1.1.0


  shared_preferences: ^0.5.7
  http:
  fluttertoast:
  geolocator: ^7.2.0+1
  location: ^2.5.4

  firebase_analytics: ^8.0.2
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.0.0






# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
